class RefreshTokenExpiredError(Exception):
    ...

class RefreshTokenNotValidError(Exception):
    ...


class AccessTokenExpiredError(Exception):
    ...

class AccessTokenNotValidError(Exception):
    ...

class TokenTypeNotValidError(Exception):
    ...

class UserAlreadyExistError(Exception):
    ...